Budgeter/Budgeter/Models/BankAccount.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Budgeter.Models
{
    public class BankAccount
    {
        public BankAccount()
        {
            this.Transactions = new HashSet<Transaction>();
        }

        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        public int HouseholdId { get; set; }
        public decimal Balance { get; set; }
        public string OwnerId { get; set; }
        public DateTimeOffset DateOpened { get; set; }
        public bool IsDeleted { get; set; }

        public virtual Household Household { get; set; }
        public virtual ApplicationUser Owner { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}

Budgeter/Budgeter/Controllers/BankAccountsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Budgeter.Models;

namespace Budgeter.Controllers
{
    [RequireHttps]
    [AuthorizeHouseholdRequired]
    public class BankAccountsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: BankAccounts
        public ActionResult Index()
        {
            var HId = Convert.ToInt32(User.Identity.GetHouseholdId());
            var bankAccounts = db.BankAccounts.Where(b => b.IsDeleted == false && b.HouseholdId == HId).Include(b => b.Household);
            return View(bankAccounts.ToList());
        }

        // GET: BankAccounts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BankAccount bankAccount = db.BankAccounts.Find(id);
            if (bankAccount == null)
            {
                return HttpNotFound();
            }
            return View(bankAccount);
        }

        // GET: BankAccounts/_Create
        public PartialViewResult _Create()
        {
            var HId = Convert.ToInt32(User.Identity.GetHouseholdId());
            var members = db.Users.Where(u => u.HouseholdId == HId);
            ViewBag.OwnerId = new SelectList(members, "Id", "DisplayName");
            return PartialView();
        }

        // POST: BankAccounts/_Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Name,Balance,DateOpened,IsDeleted,OwnerId")] BankAccount bankAccount)
        {
            var HId = Convert.ToInt32(User.Identity.GetHouseholdId());
            if (ModelState.IsValid)
            {
               
                var household = db.Households.Find(HId);
                bankAccount.HouseholdId = HId;
                bankAccount.Owner = db.Users.Find(bankAccount.OwnerId);
                bankAccount.DateOpened = System.DateTimeOffset.Now;
                bankAccount.IsDeleted = false;
                db.BankAccounts.Add(bankAccount);

                household.Accounts.Add(bankAccount);
                db.SaveChanges();
            }

            var members = db.Users.Where(u => u.HouseholdId == HId);
            ViewBag.OwnerId = new SelectList(members, "Id", "DisplayName", bankAccount.OwnerId);

            return RedirectToAction("Details", "Households");
        }

        // GET: BankAccounts/Create
        //public ActionResult Create()
        //{
        //    //ViewBag.HouseholdId = new SelectList(db.Households, "Id", "Name");
        //    return View();
        //}

        //// POST: BankAccounts/Create
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "Id,Name,HouseholdId,Balance")] BankAccount bankAccount)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.BankAccounts.Add(bankAccount);
        //        var household = db.Households.Find(bankAccount.HouseholdId);
        //        household.Accounts.Add(bankAccount);
        //        db.SaveChanges();
        //        return View();
        //    }

        //    //ViewBag.HouseholdId = new SelectList(db.Households, "Id", "Name", bankAccount.HouseholdId);
        //    return View(bankAccount);
        //}

        // GET: BankAccounts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BankAccount bankAccount = db.BankAccounts.Find(id);
            if (bankAccount == null)
            {
                return HttpNotFound();
            }
            var HId = Convert.ToInt32(User.Identity.GetHouseholdId());
            var members = db.Users.Where(u => u.HouseholdId == HId);
            ViewBag.OwnerId = new SelectList(members, "Id", "DisplayName");
            //ViewBag.HouseholdId = new SelectList(db.Households, "Id", "Name", bankAccount.HouseholdId);
            return View(bankAccount);
        }

        // POST: BankAccounts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,HouseholdId,Balance,OwnerId,DateOpened")] BankAccount bankAccount)
        {
            if (ModelState.IsValid)
            {
                bankAccount.Owner = db.Users.Find(bankAccount.OwnerId);
                db.Entry(bankAccount).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", "Households");
            }
            var members = db.Users.Where(u => u.HouseholdId == bankAccount.HouseholdId);
            ViewBag.OwnerId = new SelectList(members, "Id", "DisplayName", bankAccount.OwnerId);
            //ViewBag.HouseholdId = new SelectList(db.Households, "Id", "Name", bankAccount.HouseholdId);
            return View(bankAccount);
        }

        // GET: BankAccounts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BankAccount bankAccount = db.BankAccounts.Find(id);
            if (bankAccount == null)
            {
                return HttpNotFound();
            }
            return View(bankAccount);
        }

        // POST: BankAccounts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BankAccount bankAccount = db.BankAccounts.Find(id);
            bankAccount.IsDeleted = true;
            foreach (var transaction in bankAccount.Transactions)
            {
                transaction.IsDeleted = true;
            }
            //household.Accounts.Remove(bankAccount);
            ////db.BankAccounts.Remove(bankAccount);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //POST: BankAccounts/Reconcile
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Reconcile(int id, decimal recBalance)
        {
            BankAccount bankAccount = db.BankAccounts.Find(id);
            if (bankAccount.Balance != recBalance)
            {
                var dif = recBalance - bankAccount.Balance;
                Transaction equate = new Transaction {
                    BankAccountId = bankAccount.Id,
                    Account = bankAccount,
                    Amount = dif,
                    Date = System.DateTimeOffset.Now,
                    Description = "Reconciliation",
                    UserId = User.Identity.GetUserId(),
                    IsDeleted = false
                };
                equate.User = db.Users.Find(equate.UserId);
                if (equate.Amount <= 0)
                {
                    equate.IsWithdrawal = true;
                }
                else
                {
                    equate.IsWithdrawal = false;
                }
                bankAccount.Balance += equate.Amount;
                db.Transactions.Add(equate);
                bankAccount.Transactions.Add(equate);
                db.SaveChanges();
            }
            return RedirectToAction("Details", new { id = bankAccount.Id });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Budgeter/Budgeter/Views/BankAccounts/Create.cshtml
@model Budgeter.Models.BankAccount

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>BankAccount</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HouseholdId, "HouseholdId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("HouseholdId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.HouseholdId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Balance, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Balance, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Balance, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Budgeter/Budgeter/Views/BankAccounts/Delete.cshtml
@model Budgeter.Models.BankAccount

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BankAccount</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Household.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Household.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Balance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Balance)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Budgeter/Budgeter/Views/BankAccounts/Details.cshtml
@model Budgeter.Models.BankAccount

@{
    ViewBag.Title = "Account Details";
}

<h2>Opened: @Model.DateOpened.ToString("MMMM d, yyyy")</h2>
<h2>Primary Account Owner: @Model.Owner.DisplayName</h2>


<div class="span12">
    <div class="row text-center">
        <h1>@Html.DisplayFor(model => model.Name)</h1>
        <h2><strong>Balance: </strong>$@Html.DisplayFor(model => model.Balance)            <button href="" class="btn btn-danger open-dialog" data-toggle="modal" data-target="#reconcile"><i class="fa fa-balance-scale"></i> Reconcile</button></h2> 
        @*@Html.ActionLink("New Transaction", "Create", "Transactions", null, new { BankAccountId = Model.Id })*@
        @*<button href="" class="btn btn-primary" data-toggle="modal" data-target="#new-trans" data-hhid="@Model.Id"><i class="fa fa-money"></i> New Transaction</button>*@
    </div>
    <br />
    <div class="row-fluid">
        <div class="box span12">
            <div class="box-header" data-original-title>
                <h2><i class="fa fa-credit-card"></i><span class="break"></span>Transactions</h2>
                <div class="box-icon">
                    <a href="#" class="btn-minimize"><i class="fa fa-angle-up"></i></a>
                </div>
            </div>
            <div class="box-content">
                <table class="table-striped" id="transTable">
                    <thead>
                        <tr>
                            <th>Date</th>
                            <th>Amount</th>
                            <th>Category</th>
                            <th>Added By</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Transactions)
                        {
                            if (item.IsDeleted == false)
                            {
                                <tr>
                                    <td>
                                        @item.Date.ToString("M/d/y")
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Amount)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Category.Name)
                                    <td>
                                        @Html.DisplayFor(modelItem => item.User.DisplayName)
                                    </td>
                                    <td>
                                        @Html.ActionLink("Edit", "Edit", "Transactions", new { id = item.Id }, null) |
                                        @Html.ActionLink("Details", "Details", "Transactions", new { id = item.Id }, null) |
                                        @Html.ActionLink("Delete", "Delete", "Transactions", new { id = item.Id }, null)
                                    </td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>

            </div>
        </div><!--/span-->
        <div class="col-xs-12 col-md-5">
            <div class="box">
                <div class="box-header">
                    <h2><i class="fa fa-plus-square"></i><span class="break"></span>Create New Transaction</h2>
                </div>
                <div class="box-content">
                    @Html.Action("_Create", "Transactions", new { id = Model.Id })
                </div>
            </div>
            
        </div>
</div>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to Household", "Details", "Households", new { id = Model.HouseholdId})
</p>

@*<div class="modal fade" id="new-trans" tabindex="-1" role="dialog"
     aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"
                        aria-hidden="true">
                    ×
                </button>
                <h1 class="modal-title" id="myModalLabel">New Transaction</h1>
            </div>
            <div class="modal-body col-sm-12">

                    <div class="modal-footer no-margin">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                        <button type="submit" class="btn btn-primary">Create</button>
                    </div>
                </form>
            </div>
        </div>

    </div>
</div>*@

<!--Modal-->
<div class="modal fade" id="reconcile" tabindex="-1" role="dialog"
     aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"
                        aria-hidden="true">
                    ×
                </button>
                <h1 class="modal-title" id="myModalLabel">Reconcile Account</h1>
            </div>
            <div class="modal-body col-sm-12">
                <form role="form" method="post" action="@Url.Action("Reconcile", "BankAccounts", new { id = Model.Id })">
                    @Html.AntiForgeryToken()
                    <div class="form-group">
                        <input type="number" step="any" name="recBalance" placeholder="Balance: 0.00" />
                    </div>
                    <div class="modal-footer no-margin">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                        <button type="submit" class="btn btn-primary">Reconcile</button>
                    </div>
                </form>
            </div>
        </div>

    </div>
</div>

@section scripts{
    <script>
        $(document).ready(function () {
            $('#transTable').DataTable();
        });
    </script>
}

Budgeter/Budgeter/Views/BankAccounts/Edit.cshtml
@model Budgeter.Models.BankAccount

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>BankAccount</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.HouseholdId)
        @Html.HiddenFor(model => model.Balance)
        @Html.HiddenFor(model => model.DateOpened)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OwnerId, "Primary Account Owner", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("OwnerId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.OwnerId, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.HouseholdId, "HouseholdId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("HouseholdId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.HouseholdId, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @*<div class="form-group">
            @Html.LabelFor(model => model.Balance, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Balance, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Balance, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Household", "Details", "Households", null, null)
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Budgeter/Budgeter/Views/BankAccounts/Index.cshtml
@model IEnumerable<Budgeter.Models.BankAccount>

@{
    ViewBag.Title = "Index";
}

<h2>Bank Accounts</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Household.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Balance)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Household.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Balance)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

Budgeter/Budgeter/Views/BankAccounts/_Create.cshtml
@model Budgeter.Models.BankAccount

@using (Html.BeginForm("Create","BankAccounts")) 
{
    @Html.AntiForgeryToken()
    @*@Html.Hidden("HouseholdId")*@
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Account Name"  } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                @Html.EditorFor(model => model.Balance, new { htmlAttributes = new { @class = "form-control", @placeholder = "Balance: 0.00" } })
                @Html.ValidationMessageFor(model => model.Balance, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OwnerId, "Primary Account Owner", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("OwnerId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.OwnerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}