Budgeter/Budgeter/Models/Category.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Budgeter.Models
{
    public class Category
    {
        public Category() 
        {
            this.Transactions = new HashSet<Transaction>();
            this.BudgetItems = new HashSet<Budget>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int? HouseholdId { get; set; }
        //[UIHint("Expense")]
        [Display(Name="Type")]
        public bool IsExpense { get; set; }
        public bool IsDeleted { get; set; }

        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual ICollection<Budget> BudgetItems { get; set; }
        public virtual Household Household { get; set; }
    }
}

Budgeter/Budgeter/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Budgeter.Models;

namespace Budgeter.Controllers
{
    [RequireHttps]
    [AuthorizeHouseholdRequired]
    public class CategoriesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Categories
        public ActionResult Index()
        {
            var HId = Convert.ToInt32(User.Identity.GetHouseholdId());
            //var HBudgets = db.Budgets.Where(b => b.HouseholdId == HId).ToList();
            //var HTrans = db.Transactions.Where(t => t.Account.HouseholdId == HId).ToList();
            //var HCats = new List<Category>();
            //foreach (var bItem in HBudgets)
            //{
            //    var cat = db.Categories.Find(bItem.CategoryId);
            //    if (!HCats.Any(c => c.Id == cat.Id))
            //    {
            //        HCats.Add(cat);
            //    }
            //}
            //foreach (var trans in HTrans)
            //{
            //    var cat = db.Categories.Find(trans.CategoryId);
            //    if (!HCats.Any(c => c.Id == cat.Id))
            //    {
            //        HCats.Add(cat);
            //    }
            //}
            var HCats = db.Categories.Where(c => c.HouseholdId == HId).ToList().OrderBy(c => c.Name);
            foreach (var cat in HCats)
            {
                cat.Transactions = db.Transactions.Where(t => t.CategoryId == cat.Id && t.Account.HouseholdId == HId).ToList();
            }
            return View(HCats);
        }

        // GET: Categories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        //// GET: Categories/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        // GET: Categories/_Create
        public PartialViewResult _Create()
        {
            return PartialView();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,HouseholdId,IsExpense,IsDeleted")] Category category)
        {
            if (ModelState.IsValid)
            {
                var HId = Convert.ToInt32(User.Identity.GetHouseholdId());
                var household = db.Households.Find(HId);
                category.HouseholdId = HId;
                category.Household = household;
                category.IsDeleted = false;
                db.Categories.Add(category);
                household.Categories.Add(category);
                db.SaveChanges();
                return RedirectToAction("Index", "Budgets");
            }

            return View(category);
        }

        // GET: Categories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,HouseholdId,Household,IsExpense,IsDeleted")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Category category = db.Categories.Find(id);
            //db.Categories.Remove(category);
            category.IsDeleted = true;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Budgeter/Budgeter/Controllers/TransactionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Budgeter.Models;

namespace Budgeter.Controllers
{
    [RequireHttps]
    [AuthorizeHouseholdRequired]
    public class TransactionsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Transactions
        public ActionResult Index()
        {
            var transactions = db.Transactions.Include(t => t.Account).Include(t => t.Category).Include(t => t.User);
            return View(transactions.ToList());
        }

        // GET: Transactions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Transaction transaction = db.Transactions.Find(id);
            if (transaction == null)
            {
                return HttpNotFound();
            }
            return View(transaction);
        }

        // GET: Transactions/Create
        public PartialViewResult _Create(int? id)
        {
            //ViewBag.BankAccountId = new SelectList(db.BankAccounts, "Id", "Name");
            var HId = Convert.ToInt32(User.Identity.GetHouseholdId());
            var cats = db.Categories.Where(c => c.HouseholdId == HId);
            ViewBag.CategoryId = new SelectList(cats, "Id", "Name");
            var transaction = new Transaction();
            transaction.BankAccountId = Convert.ToInt32(id);
            return PartialView(transaction);
        }

        // POST: Transactions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,BankAccountId,UserId,CategoryId,Category,Date,Amount,IsWithdrawal,Description,IsDeleted")] Transaction transaction)
        {
            if (ModelState.IsValid)
            {
                transaction.UserId = User.Identity.GetUserId();
                transaction.User = db.Users.Find(transaction.UserId);
                transaction.Category = db.Categories.Find(transaction.CategoryId);
                transaction.Category.Transactions.Add(transaction);
                if (transaction.Amount <= 0)
                {
                    transaction.IsWithdrawal = true;
                }
                else
                {
                    transaction.IsWithdrawal = false;
                }
                transaction.IsDeleted = false;
                transaction.Date = System.DateTimeOffset.Now;
                var account = db.BankAccounts.Find(transaction.BankAccountId);
                transaction.Account = account;
                transaction.Account.Balance += transaction.Amount;
                var budget = db.Budgets.FirstOrDefault(b => b.CategoryId == transaction.CategoryId);
                if (budget != null)
                {
                    budget.Spent += transaction.Amount;
                    if (budget.Amount + budget.Spent < 0)
                    {
                        budget.IsOver = true;
                    }
                    else
                    {
                        budget.IsOver = false;
                    }
                }
                db.Transactions.Add(transaction);
                account.Transactions.Add(transaction);
                db.SaveChanges();
                return RedirectToAction("Details", "BankAccounts", new { id = transaction.BankAccountId });
            }

            //ViewBag.BankAccountId = new SelectList(db.BankAccounts, "Id", "Name", transaction.BankAccountId);
            var HId = Convert.ToInt32(User.Identity.GetHouseholdId());
            var cats = db.Categories.Where(c => c.HouseholdId == HId);
            ViewBag.CategoryId = new SelectList(cats, "Id", "Name", transaction.CategoryId);
            //ViewBag.UserId = new SelectList(db.Users, "Id", "FirstName", transaction.UserId);
            return View(transaction);
        }

        //// GET: Transactions/Create
        //public ActionResult Create()
        //{
        //    ViewBag.BankAccountId = new SelectList(db.BankAccounts, "Id", "Name");
        //    ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name");
        //    return View();
        //}

        //// POST: Transactions/Create
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "Id,BankAccountId,UserId,CategoryId,Category,Date,Amount,ReconciliationAmount,IsWithdrawal,Description,IsReconciled,IsDeleted")] Transaction transaction)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        transaction.UserId = User.Identity.GetUserId();
        //        transaction.User = db.Users.Find(transaction.UserId);
        //        if (transaction.Amount <= 0)
        //        {
        //            transaction.IsWithdrawal = true;
        //        }
        //        else
        //        {
        //            transaction.IsWithdrawal = false;
        //        }
        //        if (transaction.ReconciliationAmount > 0)
        //        {
        //            transaction.IsReconciled = false;
        //        }
        //        else
        //        {
        //            transaction.IsReconciled = true;
        //        }
        //        transaction.IsDeleted = false;
        //        transaction.Date = System.DateTimeOffset.Now;
        //        db.Transactions.Add(transaction);
        //        var account = db.BankAccounts.Find(transaction.BankAccountId);
        //        account.Transactions.Add(transaction);
        //        db.SaveChanges();
        //        return RedirectToAction("Details", "BankAccounts", new { id = transaction.BankAccountId });
        //    }

        //    //ViewBag.BankAccountId = new SelectList(db.BankAccounts, "Id", "Name", transaction.BankAccountId);
        //    ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", transaction.CategoryId);
        //    //ViewBag.UserId = new SelectList(db.Users, "Id", "FirstName", transaction.UserId);
        //    return View(transaction);
        //}

        // GET: Transactions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Transaction transaction = db.Transactions.Find(id);
            if (transaction == null)
            {
                return HttpNotFound();
            }
            var HId = Convert.ToInt32(User.Identity.GetHouseholdId());
            var accounts = db.BankAccounts.Where(a => a.HouseholdId == HId && a.IsDeleted == false);
            ViewBag.BankAccountId = new SelectList(accounts, "Id", "Name", transaction.BankAccountId);
            var cats = db.Categories.Where(c => c.HouseholdId == HId);
            ViewBag.CategoryId = new SelectList(cats, "Id", "Name", transaction.CategoryId);
            //ViewBag.UserId = new SelectList(db.Users, "Id", "FirstName", transaction.UserId);
            return View(transaction);
        }

        // POST: Transactions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,BankAccountId,UserId,CategoryId,Date,Amount,IsWithdrawal,Description,IsDeleted")] Transaction transaction)
        {
            if (ModelState.IsValid)
            {
                var OldTransaction = db.Transactions.AsNoTracking().FirstOrDefault(t => t.Id == transaction.Id);
                var account = db.BankAccounts.Find(transaction.BankAccountId);
                if (OldTransaction.BankAccountId != transaction.BankAccountId)
                {
                    var oldAccount = db.BankAccounts.Find(OldTransaction.BankAccountId);
                    oldAccount.Balance -= OldTransaction.Amount;
                    oldAccount.Transactions.Remove(transaction);
                    account.Transactions.Add(transaction);
                    account.Balance += transaction.Amount;
                }
                else
                {
                    if (OldTransaction.Amount != transaction.Amount)
                    {
                        account.Balance -= OldTransaction.Amount;
                        account.Balance += transaction.Amount;
                        //var dif = OldTransaction.Amount - transaction.Amount;
                        //account.Balance += dif;
                        var budget = db.Budgets.FirstOrDefault(b => b.CategoryId == transaction.CategoryId);
                        budget.Spent -= OldTransaction.Amount;
                        budget.Spent += transaction.Amount;
                        if (budget.Amount + budget.Spent < 0)
                        {
                            budget.IsOver = true;
                        }
                        else
                        {
                            budget.IsOver = false;
                        }

                    }
                }
                if (transaction.Amount <= 0)
                {
                    transaction.IsWithdrawal = true;
                }
                else
                {
                    transaction.IsWithdrawal = false;
                }

Budgeter/Budgeter/Views/Categories/Create.cshtml
@model Budgeter.Models.Category

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Category</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Budgeter/Budgeter/Views/Categories/Delete.cshtml
@model Budgeter.Models.Category

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Category</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Budgeter/Budgeter/Views/Categories/Details.cshtml
@model Budgeter.Models.Category

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Category</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Budgeter/Budgeter/Views/Categories/Edit.cshtml
@model Budgeter.Models.Category

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Category</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.HouseholdId)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsExpense, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*<div class="checkbox">
                    @Html.EditorFor(model => model.IsExpense)
                    @Html.ValidationMessageFor(model => model.IsExpense, "", new { @class = "text-danger" })
                </div>*@
                <select name="IsExpense">
                    <option value="true">Expense</option>
                    <option value="false">Income</option>
                </select>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Transactions By Category", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Budgeter/Budgeter/Views/Categories/Index.cshtml
@model IEnumerable<Budgeter.Models.Category>

@{
    ViewBag.Title = "Categories";
}

<h1>Transactions By Category</h1>
<hr />

@foreach (var cat in Model)
{
    var loop = 1;
    var tableId = "cat" + loop;
    <div class="row">
        <div class="box span12" ontablet="span12" ondesktop="span12">
            <div class="box-header">
                <h2><i class="fa fa-credit-card"></i><span class="break"></span>@cat.Name</h2>
                <div class="box-icon">
                    <a href="@Url.Action("Edit", "Categories", new { id = cat.Id })">Edit</a>
                    <a href="#" class="btn-minimize"><i class="fa fa-angle-up"></i></a>
                </div>
            </div>
            <div class="box-content">
                <table class="table table-striped" id="@tableId">
                    <thead>
                        <tr>
                            <th>Date</th>
                            <th>Amount</th>
                            <th>Category</th>
                            <th>User</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var transaction in cat.Transactions)
                        {
                            if (transaction.IsDeleted == false)
                            {
                                <tr>
                                    <td>
                                        @transaction.Date.ToString("M/d/y")
                                    </td>
                                    <td>
                                        $@Html.DisplayFor(modelItem => transaction.Amount)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => transaction.Category.Name)
                                    <td>
                                        @Html.DisplayFor(modelItem => transaction.User.DisplayName)
                                    </td>
                                    <td>
                                        @Html.ActionLink("Edit", "Edit", "Transactions", new { id = transaction.Id }, null) |
                                        @Html.ActionLink("Details", "Details", "Transactions", new { id = transaction.Id }, null) |
                                        @Html.ActionLink("Delete", "Delete", "Transactions", new { id = transaction.Id }, null)
                                    </td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div><!--/span-->
    </div>

}

Budgeter/Budgeter/Views/Categories/_Create.cshtml
@model Budgeter.Models.Category

@{
    ViewBag.Title = "Create Category";
}


@using (Html.BeginForm("Create", "Categories")) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsExpense, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*<div class="checkbox">
                    @Html.EditorFor(model => model.IsExpense)
                    @Html.ValidationMessageFor(model => model.IsExpense, "", new { @class = "text-danger" })
                </div>*@
                <select name="IsExpense">
                    <option value="true">Expense</option>
                    <option value="false">Income</option>
                </select>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}