Budgeter/Budgeter/Models/Budget.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Budgeter.Models
{
    public class Budget
    {
        public int Id { get; set; }
        public int HouseholdId { get; set; }
        public int CategoryId { get; set; }
        public decimal Amount { get; set; }
        public decimal Spent { get; set; }
        public bool IsOver { get; set; }

        public virtual Household Household { get; set;}
        public virtual Category Category { get; set; }
    }
}

Budgeter/Budgeter/Controllers/BudgetsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Budgeter.Models;

namespace Budgeter.Controllers
{
    [RequireHttps]
    [AuthorizeHouseholdRequired]
    public class BudgetsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Budgets
        public ActionResult Index()
        {
            var HId = Convert.ToInt32(User.Identity.GetHouseholdId());
            var HCats = db.Categories.Where(c => c.HouseholdId == HId).ToList();
            var month = DateTime.Now.Month;
            foreach (var cat in HCats)
            {
                if (cat.BudgetItems.Count == 0)
                {
                    Budget zero = new Budget
                    {
                        HouseholdId = HId,
                        CategoryId = cat.Id,
                        Category = cat,
                        Amount = 0,
                        Spent = 0,
                        IsOver = false
                    };
                    //var month = DateTime.Now.Month;
                    var transactions = db.Transactions.Where(t => t.CategoryId == cat.Id && t.IsDeleted == false && t.Date.Month == month).ToList();
                    foreach (var trans in transactions)
                    {
                        zero.Spent += trans.Amount;
                    }
                    db.Budgets.Add(zero);
                    cat.BudgetItems.Add(zero);
                }
            }
            db.SaveChanges();
            var budgets = db.Budgets.Where(b => b.HouseholdId == HId).Include(b => b.Category).ToList();
            foreach (var budget in budgets)
            {
                budget.Spent = (from t in db.Transactions
                                where t.CategoryId == budget.CategoryId && t.IsDeleted == false && t.Date.Month == month
                                select t.Amount).DefaultIfEmpty().Sum();
                if (budget.Category.IsExpense)
                {
                    if (budget.Amount + budget.Spent < 0)
                    {
                        budget.IsOver = true;
                    }
                    else
                    {
                        budget.IsOver = false;
                    }
                }
                else
                {
                    if (budget.Amount - budget.Spent < 0)
                    {
                        budget.IsOver = true;
                    }
                    else
                    {
                        budget.IsOver = false;
                    }
                }


            }
            db.SaveChanges();
            return View(budgets);
        }

        // GET: Budgets/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Budget budget = db.Budgets.Find(id);
            if (budget == null)
            {
                return HttpNotFound();
            }
            return View(budget);
        }

        //// GET: Budgets/Create
        //public ActionResult Create()
        //{
        //    ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name");
        //    return View();
        //}

        // GET: Budgets/_Create
        public PartialViewResult _Create()
        {
            var HId = Convert.ToInt32(User.Identity.GetHouseholdId());
            var cats = db.Categories.Where(c => c.HouseholdId == HId);
            ViewBag.CategoryId = new SelectList(cats, "Id", "Name");
            return PartialView();
        }

        // POST: Budgets/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,HouseholdId,CategoryId,Amount,Spent,IsOver")] Budget budget)
        {
            var HId = Convert.ToInt32(User.Identity.GetHouseholdId());
            if (ModelState.IsValid)
            {
                budget.HouseholdId = HId;
                budget.Household = db.Households.Find(HId);
                var transactions = db.Transactions.Where(t => t.CategoryId == budget.CategoryId && t.Account.HouseholdId == HId && t.IsDeleted == false).ToList();
                foreach (var trans in transactions)
                {
                    budget.Spent += trans.Amount;
                }
                if (budget.Amount + budget.Spent < 0)
                {
                    budget.IsOver = true;
                }
                else
                {
                    budget.IsOver = false;
                }
                db.Budgets.Add(budget);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            var cats = db.Categories.Where(c => c.HouseholdId == HId);
            ViewBag.CategoryId = new SelectList(cats, "Id", "Name", budget.CategoryId);
            return View(budget);
        }

        // GET: Budgets/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Budget budget = db.Budgets.Find(id);
            if (budget == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", budget.CategoryId);
            return View(budget);
        }

        // POST: Budgets/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,HouseholdId,CategoryId,Amount,Spent,IsOver")] Budget budget)
        {
            if (ModelState.IsValid)
            {
                var HId = Convert.ToInt32(User.Identity.GetHouseholdId());
                var transactions = db.Transactions.Where(t => t.CategoryId == budget.CategoryId && t.Account.HouseholdId == HId).ToList();
                foreach (var trans in transactions)
                {
                    budget.Spent += trans.Amount;
                }
                if (budget.Spent > budget.Amount)
                {
                    budget.IsOver = true;
                }
                else
                {
                    budget.IsOver = false;
                }
                db.Entry(budget).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", budget.CategoryId);
            return View(budget);
        }

        // GET: Budgets/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Budget budget = db.Budgets.Find(id);
            if (budget == null)
            {
                return HttpNotFound();
            }
            return View(budget);
        }

        // POST: Budgets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Budget budget = db.Budgets.Find(id);
            db.Budgets.Remove(budget);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Budgeter/Budgeter/Controllers/ChartsController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Budgeter.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System.Threading.Tasks;

namespace Budgeter.Controllers
{
    [RequireHttps]
    public class ChartsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Charts
        public ActionResult Index()
        {
            return View();
        }

        //GET: Spending by Category for This Month
        public ActionResult GetCatTransChart()
        {
            var HId = Convert.ToInt32(User.Identity.GetHouseholdId());
            var household = db.Households.Find(HId);
            var month = DateTime.Now.Month;

            household.Categories = db.Categories.Where(c => c.HouseholdId == HId && c.IsDeleted == false).ToList();

            var catData = (from cat in household.Categories
                           where cat.IsExpense == true
                           let sum = (from t in db.Transactions
                                      where t.CategoryId == cat.Id && t.Account.HouseholdId == HId && t.IsDeleted == false && t.Date.Month == month && t.IsWithdrawal == true
                                      select t.Amount).DefaultIfEmpty().Sum()
                           select new
                           {
                               label = cat.Name,
                               value = Math.Abs(sum)
                           }).ToArray();
            var colors = new string[] { "#0000CC", "#9900FF", "#00CC00" };
            var donut = new
            {
                cData = catData,
                chartColors = colors
            };
            return Content(JsonConvert.SerializeObject(donut), "application/json");
            //var s = new[] { new { label = "2008", value= 20 },
            //    new { label= "2008", value= 5 },
            //    new { label= "2010", value= 7 },
            //    new { label= "2011", value= 10 },
            //    new { label= "2012", value= 20 }};
            //return Content(JsonConvert.SerializeObject(s), "application/json");
        }

        //GET: Budget by Category
        public ActionResult GetBudgetCats()
        {
            var HId = Convert.ToInt32(User.Identity.GetHouseholdId());
            var household = db.Households.Find(HId);
            household.Categories = db.Categories.Where(c => c.HouseholdId == HId && c.IsDeleted == false).ToList();

            var catData = (from cat in household.Categories
                           let sum = (from b in db.Budgets
                                      where b.CategoryId == cat.Id && b.HouseholdId == HId
                                      select b.Amount).DefaultIfEmpty()
                           select new
                           {
                               label = cat.Name,
                               value = sum
                           }).ToArray();
            var colors = new string[] { "#0000CC", "#9900FF", "#00CC00" };
            var donut = new
            {
                cData = catData,
                chartColors = colors
            };
            return Content(JsonConvert.SerializeObject(donut), "application/json");

        }

        //GET: Category Budget vs Spent
        public ActionResult GetBudgvSpent()
        {
            var HId = Convert.ToInt32(User.Identity.GetHouseholdId());
            var household = db.Households.Find(HId);
            household.Categories = db.Categories.Where(c => c.HouseholdId == HId && c.IsDeleted == false).ToList();
            var month = DateTime.Now.Month;

            var catData = (from cat in household.Categories
                           where cat.IsExpense == true
                           let budget = (from b in db.Budgets
                                      where b.CategoryId == cat.Id
                                      select b.Amount).DefaultIfEmpty().Sum()
                           let spent = (from t in db.Transactions
                                      where t.CategoryId == cat.Id && t.IsDeleted == false && t.Date.Month == month && t.IsWithdrawal == true
                                      select t.Amount).DefaultIfEmpty().Sum()
                           select new
                           {
                               label = cat.Name,
                               b = budget,
                               s = Math.Abs(spent)
                           }).ToArray();
            var colors = new string[] {"#006600", "#FF0000"};
            var bar = new
            {
                cData = catData,
                chartColors = colors
            };
            return Content(JsonConvert.SerializeObject(bar), "application/json");
        }

        //GET: Income vs Expenses over month range
        public ActionResult MonthlyIncomevsExpense()
        {
            var HId = Convert.ToInt32(User.Identity.GetHouseholdId());
            var household = db.Households.Find(HId);
            var monthsToDate = Enumerable.Range(1, DateTime.Today.Month)
                    .Select(m => new DateTime(DateTime.Today.Year, m, 1))
                    .ToList();
            var sums = (from month in monthsToDate
                       select new
                       {
                           month = month.ToString("MMM"),
                           income = (from account in household.Accounts
                                     where account.IsDeleted == false
                                     from transaction in account.Transactions
                                     where transaction.IsWithdrawal == false && transaction.IsDeleted == false && transaction.Date.Month == month.Month
                                     select transaction.Amount).DefaultIfEmpty().Sum(),
                           expense = Math.Abs((from account in household.Accounts
                                      where account.IsDeleted == false
                                      from transaction in account.Transactions
                                      where transaction.IsWithdrawal == true && transaction.IsDeleted == false && transaction.Date.Month == month.Month
                                      select transaction.Amount).DefaultIfEmpty().Sum())
                       }).ToArray();
            var colors = new string[] { "#006600", "#FF0000" };
            var line = new
            {
                cData = sums,
                chartColors = colors
            };
            return Content(JsonConvert.SerializeObject(line), "application/json");
        }
    }
}

Budgeter/Budgeter/Views/Budgets/Create.cshtml
@model Budgeter.Models.Budget

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Budget</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.HouseholdId, "HouseholdId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("HouseholdId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.HouseholdId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, "CategoryId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Budgeter/Budgeter/Views/Budgets/Index.cshtml
@model IEnumerable<Budgeter.Models.Budget>

@{
    ViewBag.Title = "Budget";
}

<h1>Budget</h1>
<hr />
<div class="row">
    <div class="col-md-8">
        <div class="row">
            <div class="box span12" ontablet="span12" ondesktop="span12">
                <div class="box-header">
                    <h2><i class="fa fa-tasks"></i><span class="break"></span>Budget Items</h2>
                    <div class="box-icon">
                        <a href="#" class="btn-minimize"><i class="fa fa-angle-up"></i></a>
                    </div>
                </div>
                <div class="box-content">
                    <!-- Expense Table -->
                    <h2><strong>Expense</strong></h2>
                    <table class="table">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.Category.Name)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Amount)
                                </th>
                                <th>
                                    Spent
                                </th>
                                <th>Remaining</th>
                                <th>
                                    Status
                                </th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{ decimal bTotal = 0;}
                            @{ decimal sTotal = 0;}
                            @{ decimal rTotal = 0;}
                            @foreach (var item in Model)
                            {
                                if (item.Category.IsExpense)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Category.Name)
                                        </td>
                                        <td>
                                            $@Html.DisplayFor(modelItem => item.Amount)
                                        </td>
                                        <td>
                                            $@Math.Abs(item.Spent)
                                        </td>
                                        <td>
                                            $@(item.Amount + item.Spent)
                                        </td>
                                        <td>
                                            @if (item.IsOver)
                                            {
                                                <p class="bad">Over Budget!</p>
                                            }
                                            @if (!item.IsOver)
                                            {
                                                if (item.Amount + item.Spent == 0 && item.Spent != 0)
                                                {
                                                    <p class="bad">Stop Spending!</p>
                                                }
                                                if (item.Amount + item.Spent != 0)
                                                {
                                                    <p class="good">Keep Spending!</p>
                                                }
                                            }
                                        </td>
                                        <td>
                                            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                                            @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                                            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                                        </td>
                                    </tr>
                                            { bTotal += item.Amount; }
                                            { sTotal += item.Spent; }
                                            { rTotal += (item.Amount + item.Spent); }
                                }

                            }
                            <tr>
                                <td>
                                    <strong>Totals:</strong>
                                </td>
                                <td>
                                    <strong>$@bTotal</strong>
                                </td>
                                <td>
                                    <strong>$@Math.Abs(sTotal)</strong>
                                </td>
                                <td>
                                    <strong>$@rTotal</strong>
                                </td>
                                <td>
                                    @if (rTotal > 0)
                                    {
                                        <p class="good"><strong>Keep Spending!</strong></p>
                                    }
                                    @if (rTotal == 0)
                                    {
                                        <p class="bad">Stop Spending!</p>
                                    }
                                    @if (rTotal < 0)
                                    {
                                        <p class="bad">Over Budget!</p>
                                    }
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <!-- Income Table -->
                    <h2><strong>Income</strong></h2>
                    <table class="table">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.Category.Name)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Amount)
                                </th>
                                <th>
                                    Actual
                                </th>
                                <th>Difference</th>
                                <th>
                                    Status
                                </th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{ decimal iTotal = 0;}
                            @{ decimal aTotal = 0;}
                            @{ decimal dTotal = 0;}
                            @foreach (var item in Model)
                            {
                                if (!item.Category.IsExpense)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Category.Name)
                                        </td>
                                        <td>
                                            $@Html.DisplayFor(modelItem => item.Amount)
                                        </td>
                                        <td>
                                            $@Math.Abs(item.Spent)
                                        </td>
                                        <td>
                                            $@Math.Abs(item.Amount - item.Spent)
                                        </td>
                                        <td>
                                            @if (item.IsOver)
                                            {
                                                <p class="good">Exceeded Expectations!</p>
                                            }
                                            @if (!item.IsOver)
                                            {
                                                if (item.Amount - item.Spent == 0 && item.Spent != 0)
                                                {
                                                    <p class="good">You're Good!</p>
                                                }
                                                if (item.Amount - item.Spent != 0)
                                                {
                                                    <p class="bad">Not There Yet!</p>
                                                }
                                            }
                                        </td>
                                        <td>
                                            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                                            @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                                            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                                        </td>
                                    </tr>
                                            { iTotal += item.Amount; }
                                            { aTotal += item.Spent; }
                                            { dTotal += (item.Amount - item.Spent); }
                                }

                            }
                            <tr>
                                <td>
                                    <strong>Totals:</strong>
                                </td>
                                <td>
                                    <strong>$@iTotal</strong>
                                </td>
                                <td>
                                    <strong>$@Math.Abs(aTotal)</strong>
                                </td>
                                <td>
                                    <strong>$@Math.Abs(dTotal)</strong>
                                </td>
                                <td>
                                    @if (dTotal > 0)
                                    {
                                        <p class="bad">Keep Earning!</p>
                                    }
                                    @if (dTotal == 0)
                                    {
                                        <p class="good"><strong>You're Good!</strong></p>
                                    }
                                    @if (dTotal < 0)
                                    {
                                        <p class="good"><strong>Exceeded Expectations!</strong></p>
                                    }
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div><!--/span-->
        </div>
        <div class="row">
            <div class="box">
                <div class="box-header">
                    <h2><i class="fa fa-bar-chart"></i><span class="break"></span>Budget vs Spending By Category For This Month (dollars)</h2>
                </div>
                <div class="box-content">
                    <div id="cat-bvs" style="height: 250px;"></div>
                </div>
            </div>
        </div>
    </div>

    <!--Create New Categories and Budget Items-->
    <div class="col-md-3 col-md-offset-1">
        <div class="row">
            <div class="box">
                <div class="box-header">
                    <h2><i class="fa fa-plus-square"></i><span class="break"></span>Create New Category</h2>
                </div>
                <div class="box-content">
                    @Html.Action("_Create", "Categories")
                </div>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="box">
                <div class="box-header">
                    <h2><i class="fa fa-plus-square"></i><span class="break"></span>Create New Budget Item</h2>
                </div>
                <div class="box-content">
                    @Html.Action("_Create", "Budgets")
                </div>
            </div>
        </div>
    </div>

</div>

@section scripts{
<script>
    $(function () {
        $.post('@Url.Action("GetBudgvSpent", "Charts")').then(function (response) {
            new Morris.Bar({
                element: 'cat-bvs',
                data: response.cData,
                xkey: 'label',
                ykeys: ['b', 's'],
                labels: ['Amount Budgeted', 'Amount Spent'],
                barColors: response.chartColors,
                resize: true
            });
        });
    });
</script>

}

Budgeter/Budgeter/Views/Budgets/_Create.cshtml
@model Budgeter.Models.Budget

@{
    ViewBag.Title = "Create";
}


@using (Html.BeginForm("Create", "Budgets")) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, "Category", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}